"""
Shared security constants for the AI agent pipeline.

Single source of truth for import allowlists/blocklists, dangerous functions,
and detection thresholds. Used by both ASTSecurityScanner and PolicyLoaderTool.
"""

# Epsilon SDK modules — always safe (auto-generated by the platform)
EPSILON_SDK_MODULES = {"generated", "generated.models"}

# Imports that indicate malicious intent
BLOCKED_IMPORTS = {
    # Network access
    "socket", "urllib", "urllib.request", "urllib.parse",
    "http", "http.client", "http.server",
    "requests", "httpx", "aiohttp",
    "paramiko", "ftplib", "smtplib", "telnetlib",
    # Code execution
    "subprocess", "commands", "pty",
    # Low-level system
    "ctypes", "cffi",
    # Dangerous deserialization
    "pickle", "shelve", "marshal", "jsonpickle",
}

# Imports that are always safe for data analysis
SAFE_IMPORTS = {
    "pandas", "numpy", "scipy", "sklearn", "matplotlib", "seaborn",
    "json", "csv", "pathlib", "datetime", "math", "statistics",
    "collections", "itertools", "typing", "dataclasses", "enum",
    "re", "string", "textwrap", "io", "copy", "functools",
    "openpyxl", "xlrd", "os.path", "sys", "logging", "warnings",
    "abc", "operator", "decimal", "fractions", "random",
    "hashlib", "hmac", "pydantic", "yaml", "pyyaml",
}

# Dangerous built-in function calls
DANGEROUS_CALLS = {
    "eval", "exec", "compile", "__import__",
    "breakpoint", "exit", "quit",
}

# Dangerous attribute access patterns (module.function)
DANGEROUS_ATTRS = {
    ("os", "system"), ("os", "popen"), ("os", "exec"),
    ("os", "execl"), ("os", "execle"), ("os", "execlp"),
    ("os", "execv"), ("os", "execve"), ("os", "execvp"),
    ("os", "spawn"), ("os", "spawnl"), ("os", "spawnle"),
    ("os", "fork"), ("os", "kill"), ("os", "killpg"),
    ("os", "dup2"),
    ("os", "environ"),
    ("os", "getenv"),
    ("shutil", "rmtree"),
    ("base64", "b64decode"), ("base64", "b64encode"),
    ("base64", "decodebytes"),
}

# Env vars that are sensitive
SENSITIVE_ENV_VARS = {
    "OPENAI_API_KEY", "DATABASE_URL", "AWS_ACCESS_KEY_ID",
    "AWS_SECRET_ACCESS_KEY", "AWS_SESSION_TOKEN", "GITHUB_TOKEN",
    "GHCR_PAT", "NEON_API_KEY",
}

# URLs that are safe schema references (not exfiltration targets)
SAFE_URL_DOMAINS = {"json-schema.org", "w3.org", "schema.org"}

# Blocked function names (for policy loader display)
BLOCKED_FUNCTIONS = [
    "eval", "exec", "compile", "__import__",
    "os.system", "os.popen", "os.exec",
    "getattr",
]

# Threat tier descriptions
THREAT_TIERS = {
    "critical": "Data exfiltration, code injection, reverse shells — immediate reject",
    "high": "Filesystem escape, obfuscated code, credential harvesting — reject unless justified",
    "medium": "Suspicious imports, system reconnaissance, excessive output — flag for review",
    "low": "Minor concerns, informational — does not block execution",
}

# --- Detection thresholds ---

# Minimum base64 block length to flag as suspicious (chars)
BASE64_MIN_LENGTH = 100
# Minimum decoded base64 content size to flag (bytes)
BASE64_MIN_DECODED_SIZE = 50
# Maximum file size to read content for analysis (bytes)
OUTPUT_FILE_MAX_READ_SIZE = 10_000
# Evidence snippet truncation length (chars)
EVIDENCE_SNIPPET_LENGTH = 40
# CrewAI output truncation length (chars)
CREWAI_OUTPUT_MAX_LENGTH = 2000
# Code executor dependency install timeout (seconds)
PIP_INSTALL_TIMEOUT = 300
# Code executor script execution timeout (seconds)
SCRIPT_EXECUTION_TIMEOUT = 60

# PII field names (dataset context, not for blocking)
DEFAULT_PII_FIELDS = [
    "name", "first_name", "last_name", "email", "phone",
    "ssn", "social_security", "address", "date_of_birth", "dob",
    "patient_id", "mrn", "medical_record_number",
    "insurance_number", "credit_card", "account_number",
]
